import { createProject, projectRootPath } from '../lib/workspace/projects'
import { listFiles, readFile, createFile, updateFile, deleteFile } from '../lib/workspace/fileManager'
import { runCoder } from '../lib/agents/coder'
import { OrchestratorResult } from './index'

export async function orchestrateWithCoder(opts: { projectName?: string; prompt: string }): Promise<OrchestratorResult> {
  const logs: string[] = []
  logs.push('orchestration:start')

  // ensure project
  let project = await createProject(opts.projectName || 'Generated App')
  logs.push(`project:created:${project.id}`)

  // planner was run earlier; for safety, call planner here? We'll assume planner was run externally and is being passed in prompt.
  // For this stage, ask coder to produce operations based on prompt and existing files
  const files = await listFiles(project.id)
  const fileContents: Record<string, string> = {}
  for (const f of files) {
    try {
      fileContents[f] = await readFile(project.id, f)
    } catch (e) {
      fileContents[f] = ''
    }
  }

  logs.push('coder:start')
  let coderResp
  try {
    coderResp = await runCoder({ prompt: opts.prompt, plan: { title: 'Autogenerated' }, files, fileContents })
  } catch (err: any) {
    logs.push(`coder:error:${err.message}`)
    return { plan: null, logs }
  }

  logs.push('coder:validated')

  const applied = { created: [], updated: [], deleted: [] as string[] }

  for (const op of coderResp.operations) {
    try {
      if (op.type === 'create') {
        await createFile(project.id, op.path, op.content ?? '')
        applied.created.push(op.path)
      } else if (op.type === 'update') {
        await updateFile(project.id, op.path, op.content ?? '')
        applied.updated.push(op.path)
      } else if (op.type === 'delete') {
        await deleteFile(project.id, op.path)
        applied.deleted.push(op.path)
      }
      logs.push(`op:applied:${op.type}:${op.path}`)
    } catch (err: any) {
      logs.push(`op:error:${op.path}:${err.message}`)
    }
  }

  // Return a simple plan placeholder
  return { plan: { title: 'Coder Applied', steps: [] }, logs }
}
